"""Generate AzerothAtmosphere's Zones.lua from zones_source.py. Usage: python3 build_zones.py <out Zones.lua>"""
import sys
from math import exp
from zones_source import Z, derive_v8, safe, safe_wash, LAMP_PICKS

def mist_at(cv, d):
    """comfy's ground mist at d yards under its ground (negative: above it), at its thickest patch, over water in
    a hollow: density * exp(min(d / height, 4)) (volume.cpp FogAt), times the patches, the water and the low ground."""
    g = lambda c, dflt: cv.get(c, dflt)
    return (g("comfyMistDensity", 25) * exp(min(d / g("comfyMistHeight", 25), 4.0)) * (1 + g("comfyMistPatches", 50) / 100.0)
            * (1 + g("comfyMistWater", 210) / 100.0) * (1 + g("comfyMistLow", 150) / 100.0))

def wash_of(z):
    if z["wash"]:
        return z["wash"]
    if not z["tint"]:
        return None
    m = max(z["tint"])
    w = tuple((1 - z["k"] * (1 - c / m)) * (1 - z["dark"]) for c in z["tint"])
    return None if min(w) > 0.995 else w

def q(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

CV = [("fog", "comfyFogThickness"), ("rays", "comfyRaysStrength"), ("vol", "comfyVolumeStrength"),
      ("night", "comfyNightStrength"), ("clouds", "comfyClouds")]
def main():
    out = ["-- GENERATED by tools/build_zones.py from tools/zones_source.py. Edit the source, not this file.",
           "-- Every zone's intent (mood), where it came from (src), and the preset that goes for it.",
           "AtmosphereDirector_Zones = {"]
    for name in Z:
        z = Z[name]
        for key, _ in CV:
            v = z[key]
            assert v is None or 0 <= v <= 100, (name, key, v)
        full = {c: z[k] for k, c in CV if z[k] is not None}
        v8 = derive_v8(name)
        for c, v in v8.items():
            assert isinstance(v, int), (name, c, v)
        full.update(v8)
        held = safe(name, full)
        for c, v in held.items():   # held back, never raised; what was set by eye stays as set
            assert isinstance(v, int) and 0 <= v <= full[c], (name, c, full[c], v)
            assert c not in LAMP_PICKS.get(name, {}) or v == full[c], (name, c)
        for d in range(-100, 201, 5):  # never thicker than the full preset, at any height or depth
            assert mist_at(held, d) <= mist_at(full, d) + 1e-9, (name, d, mist_at(full, d), mist_at(held, d))
        cv = ", ".join(f"{c} = {v}" for c, v in held.items())
        w = safe_wash(name, wash_of(z))
        ws = ", wash = { %.2f, %.2f, %.2f }" % w if w else ""
        assert not w or all(0.4 <= c <= 1 for c in w), (name, w)
        out.append(f"  [{q(name)}] = {{ mood = {q(z['mood'])}, src = {q(z['src'])},")
        out.append(f"    cvars = {{ {cv} }}{ws} }},")
    out.append("}")
    open(sys.argv[1], "w", newline="\r\n" if "--crlf" in sys.argv else "\n").write("\n".join(out) + "\n")
    print(f"{len(Z)} zones written to {sys.argv[1]}")


if __name__ == "__main__":
    main()
