"""Generate AzerothAtmosphere's Zones.lua from zones_source.py. Usage: python3 build_zones.py <out Zones.lua>"""
import sys
from zones_source import Z, derive_v8

def wash_of(z):
    if z["wash"]:
        return z["wash"]
    if not z["tint"]:
        return None
    m = max(z["tint"])
    w = tuple((1 - z["k"] * (1 - c / m)) * (1 - z["dark"]) for c in z["tint"])
    return None if min(w) > 0.995 else w

def q(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

CV = [("fog", "comfyFogThickness"), ("rays", "comfyRaysStrength"), ("vol", "comfyVolumeStrength"),
      ("night", "comfyNightStrength"), ("clouds", "comfyClouds")]
def main():
    out = ["-- GENERATED by tools/build_zones.py from tools/zones_source.py. Edit the source, not this file.",
           "-- Every zone's intent (mood), where it came from (src), and the preset that goes for it.",
           "AtmosphereDirector_Zones = {"]
    for name in Z:
        z = Z[name]
        for key, _ in CV:
            v = z[key]
            assert v is None or 0 <= v <= 100, (name, key, v)
        cv = ", ".join(f"{c} = {z[k]}" for k, c in CV if z[k] is not None)
        v8 = derive_v8(name)
        for c, v in v8.items():
            assert isinstance(v, int), (name, c, v)
        cv = cv + (", " if cv and v8 else "") + ", ".join(f"{c} = {v}" for c, v in v8.items())
        w = wash_of(z)
        ws = ", wash = { %.2f, %.2f, %.2f }" % w if w else ""
        assert not w or all(0.4 <= c <= 1 for c in w), (name, w)
        out.append(f"  [{q(name)}] = {{ mood = {q(z['mood'])}, src = {q(z['src'])},")
        out.append(f"    cvars = {{ {cv} }}{ws} }},")
    out.append("}")
    open(sys.argv[1], "w", newline="\r\n" if "--crlf" in sys.argv else "\n").write("\n".join(out) + "\n")
    print(f"{len(Z)} zones written to {sys.argv[1]}")


if __name__ == "__main__":
    main()
